root: polymac/210123-53084127-A96C-4D2C-9835-90E684BE06EA
mqtt:
  useSSL: true
  timeout: 3
  server: mqtt://aliconnect.nl
  port: 1883
  root: polymac/210123-53084127-A96C-4D2C-9835-90E684BE06EA
pnode:
  host: 127.0.0.1
  port: 31863
plt:
  host: 127.0.0.1
  port: 31864
bp:
  ip: 127.0.0.1
  port: 31865
vnode_Server:
  ip: 0.0.0.0
  port_PLT: 31865
  port_BP: 31866
  csvPollingIntervalMs: 40000
expressServer:
  serverPort: 3000
PLT_Server:
  ip: 127.0.0.1
  port: 31864
BP_Server:
  ip: 127.0.0.1
  port: 31868
paths:
  outputJsonFolder: 'C:/pnode-210123/pnode-210123-plt/data/out'
  baseFile: "C:/pnode-210123/pnode-210123-aspect-file/polymac"
  baseData: "C:/pnode-210123/pnode-210123-aspect-file/data"
  baseDataPLT: "C:/pnode-210123/pnode-210123-plt/data"
  folders:
    errorInfoError: "ErrorInfo/Error"
    errorInfoProcessed: "ErrorInfo/Processed"
    finishedCartons: "FinishedCartons"
    jobChange: "JobChange"
    rejects: "Rejects"
    jobInfo: "JobInfo"
    jobInfoError: "JobInfo/Error"
    jobInfoProcessed: "JobInfo/Processed"
    logging: "Logging"
  datafiles:
    validJobs: "ValidJobs.json"
    finishedJobs: "FinishedJobs.json"
csvSettings:
  delimiter: ";"
simulatorSettings:
  csvPath: 'C:/pnode-210123/pnode-210123-aspect-file/polymac/JobInfo/BatchData.csv'
  initialJobId: "FirstJobSimID"
  jobChangeIntervalMs: 70000
  boxInfoRequestIntervalMs: 5000
  finishedCartonsIntervalMs: 5000
  rejectsIntervalMs: 5000
  mesCsvWriteIntervalMs: 15000
messagePrefixes:
  recived:
    length: 16
    jobChange: 'JOBCHANGE'
    finishedCartons: 'FINISHEDCART'
    rejects: 'REJECTS'
    boxinfo: 'REQUESTBOXINFO'
  send:
    length: 8
    jobChangeInfo: 'Job:'
    boxInfo: 'Job:'
finishedCartons:
  startDateAndTime:
    name: 'startTime'
  JobID:
    name: 'JobID'
  finishedCartons:
    name: 'FinishedCartons'
  boxQtyActual:
    name: 'BoxQtyActual'
  rejectQty:
    name: 'RejectQty'
  endDateAndTime:
    name: 'endTime'
schemas:
  batchData:
    filename: BatchData.csv
    properties:
      JobID:
        usedby: PLC
        length: 40
      JobRun:
        usedby: PLC
        length: 4
      DesiredYield:
        usedby: PLC
        length: 8
      MaterialID:
        usedby: PLC
        length: 30
      ScheduleIndex:
        usedby: PLC
        length: 4
      LBLBARCODE:
        usedby: PLC
        length: 40
      LBLNAME:
        usedby: PLC
        length: 120
      IMLBARCODE:
        usedby: PLC
        length: 40
      IMLBARCODELOC:
        usedby: PLC
        length: 4
        options:
          - value: false
          - value: "B"
          - value: "T"
  jobInfo:
    sender: vnode
    properties:
      JobIDCurrent:
        length: 40
        name: JobID
      DesiredYieldCurrent:
        length: 8
        name: DesiredYield
      MaterialID:
        length: 40
        name: MaterialID
      LBLNAME:
        length: 120
        name: LBLNAME
      LBLBARCODECurrent:
        length: 40
        name: LBLBARCODE
      IMLBARCODECurrent:
        length: 40
        name: IMLBARCODE
      IMLBARCODELOCCurrent:
        length: 4
        name: IMLBARCODELOC
      JobIDNext:
        length: 40
        name: JobID
      LBLBARCODENext:
        length: 40
        name: LBLBARCODE
      IMLBARCODENext:
        length: 40
        name: IMLBARCODE
      IMLBARCODELOCNext:
        length: 4
        name: IMLBARCODELOC
      DesiredYieldNext:
        length: 8
        name: DesiredYield
      DateTime:
        length: 16
        name: DateTime
  rejects:
    filename: 'Rejects.csv'
    sender: plt
    properties:
      jobID:
        length: 40
        name: JobID
      rejectReasonCode:
        length: 40
        name: RejectReasonCode
      quantity:
        length: 40
        name: Quantity
  jobChange:
    sender: plt
    filename: 'JobChange.csv'
    properties:
      dataCount:
        length: 8
      jobID:
        length: 40
        name: JobID
      jobRun:
        length: 40
        name: JobRun
  finishedCartons:
    filename: 'FinishedCartons.csv'
    properties:
      jobID:
        length: 40
        name: JobID
      numberOfFinishedCartons:
        length: 8
        name: FinishedCartons
      boxQtyActual:
        length: 8
        name: BoxQtyActual
  boxinfo:
    sender: bp
    properties:
      jobID:
        length: 40
        name: JobID
      MaterialID:
        length: 40
        name: MaterialID
      LBLBARCODE:
        length: 40
        name: LBLBARCODE
      LBLNAME:
        length: 120
        name: LBLNAME
      DateTime:
        length: 16
        name: DateTime
  genralRecivePrefix:
    context:
      length: 16
    dataCount:
      length: 8
